---
- name: Check for Composer
  stat: path={{ composer_dir }}/composer.phar
  register: composer_result

- name: Download Composer Installer
  get_url: url=https://getcomposer.org/installer dest=/tmp/install-composer.php
  when: not composer_result.stat.exists

- name: Create Composer Directory
  file: path={{ composer_dir }} state=directory

- name: Install Composer
  phpenv:
    shell: php /tmp/install-composer.php --install-dir={{ composer_dir }}
    creates: "{{ composer_dir }}/composer.phar"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  notify: Rehash Phpenv

- name: Install Composer Packages
  phpenv:
    shell: "composer global require {{ item.name }}:{{ item.version }} --prefer-dist --no-interaction"
    creates: "{{ composer_dir }}/vendor/{{ item.name }}"
    phpenv_root: "{{ phpenv_root }}"
    php_version: "{{ php_version }}"
  register: composer_result
  changed_when:
    - composer_result is changed
    - "'Nothing to install or update' not in composer_result.stderr"
  notify: Rehash Phpenv
  loop: "{{ composer_packages | default([]) }}"
