require "serverspec"

shared_examples "no errors" do
  it "should have no errors" do
    # HAX! Strip errors generated by Docker
    subject.stderr.gsub!(/stdin: is not a tty\n?/, '')
    subject.stderr.gsub!(/mesg: ttyname failed: Inappropriate ioctl for device\n?/, '')

    expect(subject.stderr).to eq ""
    expect(subject.exit_status).to eq 0
  end
end
